name: Docker Image CI - ms-signin

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image to ms-signin
        run: cd ms-signin && docker build . --file Dockerfile --tag my-image-name:$(date +%s)
